# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import exchange_pb2 as exchange__pb2


class ExchangeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StreamRates = channel.unary_stream(
        '/exchange.Exchange/StreamRates',
        request_serializer=exchange__pb2.ExchangeRateRequest.SerializeToString,
        response_deserializer=exchange__pb2.CurrencyRate.FromString,
        )


class ExchangeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StreamRates(self, request, context):
    """rpc CurrentRates(ExchangeRateRequest) returns (ExchangeRateResponse) {}
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExchangeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StreamRates': grpc.unary_stream_rpc_method_handler(
          servicer.StreamRates,
          request_deserializer=exchange__pb2.ExchangeRateRequest.FromString,
          response_serializer=exchange__pb2.CurrencyRate.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'exchange.Exchange', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
